name: minttask
description: "A new Flutter project."
publish_to: 'none' 

version: 2.0.0+200

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  flutter_riverpod: ^2.5.1
  dynamic_color: ^1.7.0
  go_router: ^14.1.1
  animations: ^2.0.11
  file_picker: ^8.0.3
  path: ^1.9.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10


flutter:

  uses-material-design: true
  assets:
    - CHANGELOG.md
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope/Manrope-Regular.ttf
        - asset: fonts/Manrope/Manrope-Bold.ttf
          weight: 700
        - asset: fonts/Manrope/Manrope-Light.ttf
          weight: 300
