name: minttask
description: A simple todo manager for Android made using Flutter with Material Design 3.

publish_to: 'none'

version: 2.0.0+200

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animations: ^2.0.7
  archive: ^3.4.9
  awesome_notifications: any
  awesome_notifications_core: ^0.8.0
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.6.5
  file_picker: ^8.0.0+1
  fleather: ^1.11.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.6
  flutter_whatsnew: ^1.0.5+2
  intl: ^0.18.1
  markdown_quill:
    git: https://github.com/boredcodebyk/markdown_quill
  marquee: ^2.2.3
  material_color_utilities: ^0.5.0
  package_info_plus: ^4.0.2
  parchment: ^1.11.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.3.0
  provider: ^6.0.5
  quick_actions: ^1.0.6
  quick_settings: ^1.0.1
  restart_app: ^1.2.1
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+4
  timezone: ^0.9.2
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint:
  riverpod_lint: ^2.3.10
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/github-mark-white.svg
    - assets/github-mark.svg
    - CHANGELOG.md
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope/Manrope-Regular.ttf
  #      - asset: fonts/Schyler-Italic.ttf
  #        style: italic
