name: minttask
description: A simple todo manager for Android made using Flutter with Material Design 3.

publish_to: "none"

version: 2.0.0+200

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animations: ^2.0.7
  appflowy_editor: ^3.1.0
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.6
  go_router: ^14.2.3
  intl: ^0.19.0
  material_color_utilities: ^0.11.1
  package_info_plus: ^8.0.2
  path: ^1.8.3
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.3.3
  url_launcher: ^6.1.11
  uuid: ^4.4.2

dev_dependencies:
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/github-mark-white.svg
    - assets/github-mark.svg
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope/Manrope-Regular.ttf
  #      - asset: fonts/Schyler-Italic.ttf
  #        style: italic
